# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170622_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to='core.Product'),
        ),
        migrations.AlterField(
            model_name='productquestionchoice',
            name='product_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.ProductQuestion'),
        ),
        migrations.AlterField(
            model_name='productrow',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rows', to='core.Inquiry'),
        ),
        migrations.AlterField(
            model_name='productrow',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rows', to='core.Proposal'),
        ),
    ]
